	<div class="card-footer">
		<p>R. Prabucki recruitment task for Aurora Creations</p>
	</div>
	</div>
</body>




	<!-- JS -->
	<script src="assets/jquery.min.js"></script>
	<script src="assets/bootstrap.min.js"></script>
	<script src="assets/jquery.dataTables.min.js"></script>
	<script src="assets/dataTables.bootstrap4.min.js"></script>
	<script src="assets/jquery.validate.min.js"></script>
	<script src="assets/additional-methods.min.js"></script>
	<script src="assets/jquery-confirm.js"></script>
	<script>
	$(document).ready(function () {
	  $("#flash-msg").delay(7000).fadeOut("slow");
	});
	$(document).ready(function() {
	  $('.table').DataTable();
	} );	
	</script>
	<?php require_once PATH_CONFIG . DS . 'config-form-js.phtml'; ?>
</html>