<!DOCTYPE html>
<html lang="pl" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title><?php echo $pageTitle ? $pageTitle.' - ' : ''; ?>R. Prabucki recruitment task for Aurora Creations</title>
		<link rel="stylesheet" href="assets/bootstrap.min.css">
		<link href="assets/fontawesome/css/all.min.css" rel="stylesheet">
		<link rel="stylesheet" href="assets/dataTables.bootstrap4.min.css">
		<link rel="stylesheet" href="assets/jquery-confirm.css">
		<link rel="stylesheet" href="assets/style.css">
	</head>
	
	<body>
  
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="#">Admin Demo</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link active" href="./"><i class="fas fa-list mr-2"></i>Articles list</a>
				</li>
			</ul>
		</div>
	</nav>