<div class="container mt-3 mb-3">
	<div class="row">
		<div class="col-sm">
			<h2>Article <?php if($get['mode'] == 'edit' and is_numeric($get['article_id'])){ ?>edition<?php } if($get['mode'] == 'edit' and !isset($get['article_id'])){ ?>creation<?php } ?>
				<a class="float-right btn btn-sm btn-light" href="./"><i class="fas fa-angle-double-left m-2"></i>back to articles list</a>
			</h2>
			<div class="card">
			<div class="card-body">
				<div>

				<form id="articleForm" class="" action="" method="POST">
					<div class="form-group">
						<label for="article_title">Article title</label>
						<input type="text" name="article_title" placeholder="Article title here" value="<?php echo htmlspecialchars_decode($system->articleData['article_title']); ?>" class="form-control" />
					</div>

					<div class="form-group">
						<label for="comment">Article description</label>
						<textarea name="article_description" placeholder="Article description here" rows="5" id="article_description" class="form-control" ><?php echo htmlspecialchars_decode($system->articleData['article_description']); ?></textarea>
					</div> 

					<div class="form-group">
						<div class="form-group">
							<label for="sel1">Article status</label>
							<select class="form-control" name="article_status" id="article_status">
								<?php 
								foreach (ARTICLE_STATUS as $index => $status) { ?>
								<option value="<?php echo $index;?>" <?php echo $system->articleData['article_status'] == $index ? 'selected="selected"' : '';?>><?php echo $status;?></option>
								<?php } ?>
							</select>
						</div>
					</div>
<?php /* TODO: Article category
					<div class="form-group">
						<div class="form-group">
							
							<label for="sel1">Article category</label>
							<select class="form-control" name="article_category" id="article_status">
								<?php 
								foreach (ARTICLE_CATEGORY as $index => $status) { ?>
								<option value="<?php echo $index;?>" <?php echo $system->articleData['article_category'] == $index ? 'selected="selected"' : '';?>><?php echo $status;?></option>
								<?php } ?>
							</select> 
							
						</div>
					</div>
*/ ?>
					<div class="form-group">
						<?php if($get['mode'] == 'edit' and is_numeric($get['article_id'])){ ?>
						<input type="hidden" name="article_id" value="<?php echo $get['article_id']; ?>" />
						<input type="hidden" name="update" value="true" />
						<button type="submit" class="btn btn-success">Update</button>
						<?php } ?>
						<?php if($get['mode'] == 'edit' and !isset($get['article_id'])){ ?>
						<input type="hidden" name="create" value="true" />
						<button type="submit" class="btn btn-success">Create</button>
						<?php } ?>
						<span class="ml-2" id="formSubmitInfo"></span>
					</div>
				</form>
				</div>

				</div>
			</div>
		</div>
	</div>
</div>