<div class="container mt-3 mb-3">
	<div class="row">
		<div class="col-sm">
			<h2>Articles list <a class="float-right btn btn-sm btn-light" href="?mode=edit"><i class="fas fa-plus mr-2"></i>add new</a></h2>
			<table id="articlesTable" class="text-center table table-sm table-striped table-bordered">
				<thead>
					<tr>
						<th>ID</th>
						<th>Title</th>
						<th>Description</th>
						<th>Status</th>
						<th>Actions</th>
					</tr>
				</thead>
				
				<tbody>				
					<?php
					if ($system->articlesData) { //If not empty
					foreach ($system->articlesData as $id=>$value) { //Generate articles list
					?>
					<tr>
						<td><?php echo $id; ?></td>
						<td><?php echo htmlspecialchars_decode($value['article_title']); ?></td>
						<td><div style="white-space:pre=wrap;"><?php echo htmlspecialchars_decode($value['article_description']); ?></div></td>
						<td><?php echo ARTICLE_STATUS[$value['article_status']]; ?></td>
						<td>
							<a href="?mode=edit&article_id=<?php echo $id; ?>"><span class="btn btn-sm btn-light"><i class="fas fa-edit mr-2"></i>edit</span></a>
							<span data-id="<?php echo $id; ?>" class="articleRemoveBtn btn btn-sm btn-light"><i class="fas fa-trash-alt mr-2"></i>remove<i class="d-none fas fa-circle-notch fa-spin ml-2" ></i><i class="d-none fas fa-check ml-2" ></i></span>
						</td>
					</tr>
					<?php }} else { //No articles = empty db ?>
					<tr>
						<td colspan="5">No articles</td>
					</tr>
				</tbody>
				<?php } ?>
				<tfoot>
					<tr>
						<th>ID</th>
						<th>Title</th>
						<th>Description</th>
						<th>Status</th>
						<th>Actions</th>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>